#The input files
#This is the random file for the clustering catalogue. 
expect_file = /global/cfs/cdirs/desi/science/td/pv/bgsclustering/BGS_BRIGHT_clustering_forPV_random.fits

#The data catalogues
datafile_pv = /global/cfs/cdirs/desi/science/td/pv/combinedpv/Y1/PV_clustering_data_v5_v13.fits
datafile_gal = /global/cfs/cdirs/desi/science/td/pv/bgsclustering/BGS_BRIGHT_clustering_forPV_data.fits
#The type of the input files. Only supports "csv" and "fits" (case sensitive)
filetype = fits
#Whether the RA and Dec in the data files are in degrees. Enter 1 if they are in degrees or 0 otherwise. 
deg = 1
#The header for RA 
RA_header = RA
#The header for Dec
Dec_header = DEC
#The header for redshift
redshift_header = Z
#The header for the logdistance ratio 
logdist_header = LOGDIST
#The header for the logdistance ratio error
logdist_err_header = LOGDIST_ERR
#The sigma cut on the logdistance ratio 
sigma_cut = 4
#The overdensity cut for the galaxy. Should be less than 100 and greater than 1. 
overdensity_cut = 10.0
#The number of grids for Taylor expansion per parameter 
N_grid = 9
#The number of naive parallelization
N_parallel = 9
#Using mock or data. Enter 1 for using the mock or 0 for using the data. 
mock_data = 0

#The input variables (The covariance matrix code assumes f=b=1, but sigma8 should be calculated based on the cosmology of the simulation)
#The fiducial value of matter density \Omega_m of the universe at redshift zero. 
#omega_m = 0.3121
omega_m = 0.31377
#The fiducial fsigma8 used to generate the covariance matrix. Beaware that the covariance matrix assumes f = 1. 
#fsigma8_old = 0.8150
fsigma8_old = 0.80975
#The uncertainty of the zero-point correction 
sigma_b = 0.0063
#The value of bsigma8 used to generate the covariance matrix. The fiducial value for b is 1. 
#bsigma8_old = 0.8150
bsigma8_old = 0.80975
#The galaxy-matter cross-correlation coefficient (set to one).
r_g = 1.0
#The fiducial matter density at redshift zero. 
kmin = 0.0002 
#The kmax for the covariance matrix 
kmax = 0.20
#The kmax for the galaxy density analysis 
kmax_galaxy = 0.20 
#The kmax for the velocity analysis (Typically the same as the galaxy density) 
kmax_velocity = 0.20 
#The grid size of smoothing 
gridsize = 20 
#Whether or not to print out the progress during the MCMC (Enter 1 for True, 0 for False)
progress = 1
#The value of sigmau to use 
sigma_u = 16.0
#The initial guess for sigmag during optimization
sigma_g = 1.0
#The effective redshift of the survey 
effective_redshift = 0.071
#The value of sigma8 at the effective redshift with the fiducial cosmology 
sigma8_eff = 0.785
#The grid used to generate the covariance matrix
xmin = -300.0
xmax = 300.0
ymin = -300.0
ymax = 300.0
zmin = -100.0 
zmax = 300.0 

#The kmin and kmax for the badd covariance matrix calculation
kmin_badd = 0.200 
kmax_badd = 0.999

#The P0 used for the FKP weight of galaxy density and peculiar velocity
P0_dens = 1600.0
P0_vel = 5e9
sigma_v_fid = 300.0
#The weight for galaxy density and log-distance ratio. Eneter 'none' for no weight, 'invar' for inverse variance weight on pv, 'full' for FKP and incompleteness weight for both. 
weight = full
#redshift cut
red_cut = 0.05

#The power spectrum file containing k mode in the first column, pmm in the second column, pmv in the third column, and pvv in the fourth column.
#pkvelfile = /global/u2/y/ylai1998/Peculiar_velocity_fitting/grid_correction/rpt2_waves_input_new.dat
pkvelfile = /global/u2/y/ylai1998/Peculiar_velocity_fitting/grid_correction/PS_model_SPT_z_0.071_omegam_0.314.dat
#The name of the covariance matrix 
#covfile_base = /pscratch/sd/y/ylai1998/desi_pv/DESI
covfile_base = /pscratch/sd/y/ylai1998/desi_pv/DESI_SPT_data
#The name of the grid correction file 
gridcorrfile = /global/u2/y/ylai1998/Peculiar_velocity_fitting/grid_correction/gridcorr_30.dat
#The name of the survey
name = DESI
#The total number of mocks
mock_tot = 675
#The total number of parallel jobs
job_tot = 27
#The Perturbation Theory (Either RPT or SPT). Recommend using the SPT model. 
PT_method = SPT

#tr(M*(-1/2*inv(C) + 1/2*inv(C)*s*s'*inv(C) + inv(C)*x*x'*inv(C)/(2*(x'*inv(C)*x + 1/y^2)) + 1/(4*(x'*inv(C)*x + 1/y^2)^2)*(-4*(x'*inv(C)*x + 1/y^2)*(s'*inv(C)*x)*inv(C)*s*x'*inv(C) + 2*(s'*inv(C)*x)^2*inv(C)*x*x'*inv(C))))